server:
  port: 8080

okta:
  oauth2:
    issuer: https://dev-xxx.okta.com/oauth2/default
    client-id: xxx
    client-secret: xxx

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: xxx.apps.googleusercontent.com
            client-secret: xxx

